<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation=
         "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.trupti</groupId>
  <artifactId>org.trupti.BDD</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
	<!--  for web site automation -->
	<dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-java</artifactId>
	    <version>4.46.0</version>
	</dependency>
	<!--  for Framework -->
	<dependency>
	    <groupId>org.testng</groupId>
	    <artifactId>testng</artifactId>
	    <version>7.10.2</version>
	</dependency>
	<dependency>
	    <groupId>io.cucumber</groupId>
	    <artifactId>cucumber-java</artifactId>
	    <version>7.33.0</version>
	</dependency>
	<dependency>
	    <groupId>io.cucumber</groupId>
	    <artifactId>cucumber-testng</artifactId>
	    <version>7.33.0</version>
	</dependency>
	<dependency>
	    <groupId>io.cucumber</groupId>
	    <artifactId>cucumber-picocontainer</artifactId>
	    <version>7.33.0</version>
	</dependency>
	<!-- for additional reporting -->
	<dependency>
	    <groupId>tech.grasshopper</groupId>
	    <artifactId>extentreports-cucumber7-adapter</artifactId>
	    <version>1.10.1</version>
	</dependency>
	<dependency>
	    <groupId>io.qameta.allure</groupId>
	    <artifactId>allure-cucumber7-jvm</artifactId>
	    <version>2.35.2</version>
	</dependency>
	<!--  for excel file -->
	<dependency>
	    <groupId>org.apache.poi</groupId>
	    <artifactId>poi-ooxml</artifactId>
	    <version>5.4.1</version>
	</dependency>
	
	<!--  for full page screenshot if required -->
	<dependency>
    	<groupId>ru.yandex.qatools.ashot</groupId>
    	<artifactId>ashot</artifactId>
    	<version>1.5.4</version>
	</dependency>	
	<!--  for other jars if required -->
  </dependencies>
  <!--  for maven plug-ins -->
  <build>
   <plugins>
      <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.15.0</version>
             <configuration>
                 <source>21</source>
                 <target>21</target>
             </configuration>
       </plugin>
       <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-surefire-plugin</artifactId>
           <version>3.5.5</version>
	   	   <configuration>
	      		<suiteXmlFiles>
					<suiteXmlFile>${xyz}</suiteXmlFile>
	      		</suiteXmlFiles>
	   	   </configuration>
         </plugin>
     </plugins>
   </build>
</project>
