#My results Properties file
#Fri Sep 15 07:47:05 IST 2023
name=Mr. abdul kalam sir
email=apj@abdulkalam.com
#Data from Jessy
#Fri Sep 15 07:48:34 IST 2023
testleadname=abdul kalam1234567
testleademail=apj1234567@abdulkalam.com
